[package]
name = "rust-injector"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "lib"
proc-macro = true

[dependencies]
nix = "0.23.1"
regex = "1.5.4"
